aiog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('exercicios/', include('exercicios.urls')),
#    path('comentarios/', include('comentarios.urls')),
#    path('accounts/', include('accounts.urls')),
#    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
#    path('api/v1/', include('api.urls')),
]

exercicios/urls.py
from django.urls import path

from . import views

app_name = 'exercicios'
urlpatterns = [
    path('', views.ExercicioListView.as_view(), name='index'),
#    path('search/', views.search_exercicios, name='search'),
    path('create/', views.create_exercicio, name='create'),
    path('<int:exercicio_id>/', views.detail_exercicio,
         name='detail'), 
    path('update/<int:exercicio_id>/', views.update_exercicio, name='update'),
    path('delete/<int:exercicio_id>/', views.delete_exercicio, name='delete'),
    path('<int:exercicio_id>/comment/', views.create_comment, name='comment'),
    path('categorias/', views.CategoryListView.as_view(), name='categorias'),
    path('categorias/create_categoria', views.CategoryCreateView.as_view(), name='create_categoria'),
#    path('import/', views.import_exercicio, name='import'),
]

exercicios/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


class Exercicio(models.Model):
    data_publicacao = models.DateTimeField(default=timezone.now)
    imagem_card_url = models.URLField(max_length=999, null=True)
    nome_exercicio = models.CharField(max_length=999, default="")
    descricao_exercicio = models.TextField(default="")
    texto_html = models.TextField(default="")
    imagem_post_url = models.URLField(max_length=999, null=True)


class Comment(models.Model):
    data_publicacao = models.DateTimeField(default=timezone.now)
    autor = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    texto = models.CharField(max_length=255)
    likes = models.IntegerField(default=0)
    post = models.ForeignKey(Exercicio, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.texto}" - {self.autor.username}'


class Category(models.Model):
    nome_categoria = models.CharField(max_length=255, default="")
    descricao_categoria = models.CharField(max_length=255, default="")
    exercicios = models.ManyToManyField(Exercicio)

    def __str__(self):
        return f'{self.nome_categoria}'

exercicios/forms.py
from django.forms import ModelForm
from .models import Exercicio, Comment, Category


class ExercicioForm(ModelForm):
    class Meta:
        model = Exercicio
        fields = [
            'imagem_card_url',
            'nome_exercicio',
            'descricao_exercicio',
            'texto_html',
            'imagem_post_url',
        ]
        labels = {
            'imagem_card_url': 'URL da imagem para o card',
            'nome_exercicio': 'Nome do exercício',
            'descricao_exercicio': 'Descrição do exercício',
            'texto_html': 'Código em html do conteúdo do post',
            'imagem_post_url': 'URL da imagem para o post',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'autor',
            'texto',
        ]

        labels = {
            'autor': 'Autor da publicação',
            'texto': 'Seu comentário',
        }

class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = [
            'nome_categoria', 
            'descricao_categoria',
            'exercicios',
        ]

        labels = {
            'nome_categoria': 'Nome da categoria/tag',
            'descricao_categoria': 'Descrição da categoria/tag',
            'exercicios': 'Exercícios que serão incluídos na categoria/tag',
        }

exercicios/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from .models import Exercicio, Comment, Category
from .forms import ExercicioForm, CommentForm, CategoryForm



class ExercicioListView(generic.ListView):
    model = Exercicio
    template_name = 'exercicios/index.html'




def detail_exercicio(request, exercicio_id):
    exercicio = get_object_or_404(Exercicio, pk=exercicio_id)
    context = {'exercicio': exercicio}
    return render(request, 'exercicios/detail.html', context)





def search_exercicio(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        lista_exercicios = Exercicio.objects.filter(name__icontains=search_term)
        context = {"lista_exercicios": lista_exercicios}
    return render(request, 'exercicios/search.html', context)





def create_exercicio(request):
    if request.method == 'POST':
        form = ExercicioForm(request.POST)
        if form.is_valid():
            imagem_card_url = form.cleaned_data['imagem_card_url']
            nome_exercicio = form.cleaned_data['nome_exercicio']
            descricao_exercicio = form.cleaned_data['descricao_exercicio']
            texto_html = form.cleaned_data['texto_html']
            imagem_post_url = form.cleaned_data['imagem_post_url']
            exercicio = Exercicio(imagem_card_url=imagem_card_url,
                        nome_exercicio=nome_exercicio,
                        descricao_exercicio=descricao_exercicio,
                        texto_html=texto_html,
                        imagem_post_url=imagem_post_url)
            exercicio.save()
            return HttpResponseRedirect(
                reverse('exercicios:detail', args=(exercicio.id, )))
    else:
        form = ExercicioForm()
    context = {'form': form}
    return render(request, 'exercicios/create.html', context)




def update_exercicio(request, exercicio_id):
    exercicio = get_object_or_404(Exercicio, pk=exercicio_id)

    if request.method == "POST":
        form = ExercicioForm(request.POST)
        if form.is_valid():
            imagem_card_url = form.cleaned_data['imagem_card_url']
            nome_exercicio = form.cleaned_data['nome_exercicio']
            descricao_exercicio = form.cleaned_data['descricao_exercicio']
            texto_html = form.cleaned_data['texto_html']
            imagem_post_url = form.cleaned_data['imagem_post_url']
            exercicio = Exercicio(imagem_card_url=imagem_card_url,
                        nome_exercicio=nome_exercicio,
                        descricao_exercicio=descricao_exercicio,
                        texto_html=texto_html,
                        imagem_post_url=imagem_post_url)
            exercicio.save()
            return HttpResponseRedirect(
                reverse('exercicios:detail', args=(exercicio.id, )))
    else:
        form = ExercicioForm(
            initial={
                'imagem_card_url': exercicio.imagem_card_url,
                'nome_exercicio': exercicio.nome_exercicio,
                'descricao_exercicio': exercicio.descricao_exercicio,
                'texto_html': exercicio.texto_html,
                'imagem_post_url': exercicio.imagem_post_url,
            })
    context = {'exercicio': exercicio, 'form': form}
    return render(request, 'exercicios/update.html', context)





def delete_exercicio(request, exercicio_id):
    exercicio = get_object_or_404(Exercicio, pk=exercicio_id)

    if request.method == "POST":
        exercicio.delete()
        return HttpResponseRedirect(reverse('exercicios:index'))

    context = {'exercicio': exercicio}
    return render(request, 'exercicios/delete.html', context)



def create_comment(request, exercicio_id):
    exercicio = get_object_or_404(Exercicio, pk=exercicio_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_autor = form.cleaned_data['autor']
            comment_texto = form.cleaned_data['texto']
            comment = Comment(autor=comment_autor,
                            texto=comment_texto,
                            post = exercicio)
            comment.save()
            return HttpResponseRedirect(
                reverse('exercicios:detail', args=(exercicio_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'exercicio': exercicio}
    return render(request, 'exercicios/comment.html', context)




class CategoryListView(generic.ListView):
    model = Category
    template_name = 'exercicios/categorias.html'


class CategoryCreateView(generic.CreateView):
    model = Category
    template_name = 'exercicios/create_categoria.html'
    fields = ['nome_categoria', 'descricao_categoria', 'exercicios']
    success_url = reverse_lazy('exercicios:categorias')

exercicios/templates/exercicios/categorias.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Lista de categorias/tags</h2>

{% if object_list %}
    {% for categoria in object_list %}
    <hr>
    <article>
        <h3>- {{categoria.nome_categoria}}</h3>
        <p>{{ categoria.descricao_categoria }}</p>
        <div class="lista-de-cards">
        {% for exercicio in categoria.exercicios.all %}
            <div class="card text-center" style="width: 18rem;">
                <a href="{% url 'exercicios:detail' exercicio.id %}">
                    <img class="card-img-top" src="{{ exercicio.imagem_card_url }}" alt="{{exercicio.nome_exercicio}}" height="200px">
                </a>
                <div class="card-body">
                    <h5 class="card-title" id="fonte-preta">{{ exercicio.nome_exercicio }}</h5>
                </div>
            </div>
            <br>
        {% endfor %}
        </div>
    </article>
    {% endfor %}
{% else%}
    <p>Não há nenhuma categoria ainda.</p>
{% endif %}



<a href="{% url 'exercicios:create_categoria' %}"><button>Adicionar categoria</button></a>


{% endblock content %}

exercicios/templates/exercicios/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentário para o post: {{ exercicio.nome_exercicio }}</h2>

<form action="{% url 'exercicios:comment' exercicio.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Publicar</button>
</form>

<br>
<br>
<a href="{% url 'exercicios:detail' exercicio.id %}"><p>◀ Voltar para o post</p></a>
{% endblock content %}

exercicios/templates/exercicios/create.html
{% extends 'base.html' %}


{% block content %}

<h2>Inserir novo exercício</h2>

<form method="POST" action="{% url 'exercicios:create' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Criar</button>
</form>


{% endblock content %}

exercicios/templates/exercicios/create_categoria.html
{% extends 'base.html' %}


{% block content %}

<h2>Inserir nova categoria</h2>

<form method="POST" action="{% url 'exercicios:create_categoria' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Criar</button>
</form>


{% endblock content %}

exercicios/templates/exercicios/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'exercicios:delete' exercicio.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o exercício "{{ exercicio.nome_exercicio }}"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

exercicios/templates/exercicios/detail.html
{% extends 'base.html' %}

{% block title %}
{{ exercicio.nome_exercicio }}
{% endblock title %}

{% block content %}
<div style="width: 100; display: flex; padding-left: 10px; padding-right: 10px; flex-wrap: wrap; justify-content:center ">
    <a href="{% url 'exercicios:update' exercicio.id %}"><button type="submit">Alterar dados do exercício</button></a>
    <div style="width: 10px;"></div>
    <a href="{% url 'exercicios:delete' exercicio.id %}"><button type="submit">Deletar exercício</button></a>
</div>




<h2>{{ exercicio.nome_exercicio }}</h2>
<p>{{ exercicio.descricao_exercicio }}</p>
<br>

<div class="bloco-exercicios">
    <div class="texto-exercicios">
        {{ exercicio.texto_html | safe }}
    </div>
    <div class="imagem-exercicios">
        <img src="{{ exercicio.imagem_post_url }}" alt="{{ exercicio.nome_exercicio }}" width="80%" height="100%" style="border-radius: 20px;">
    </div>
</div>
<br>

<p>Postado em {{ exercicio.data_publicacao | date }}</p>
<br>
<br>

{% if exercicio.category_set.all %}
    <p>Exercício presente nas tags: {{ exercicio.category_set.all|join:", " }}</p>
{% endif %}

<br>
<br>

<section style="border: 3px solid white; border-radius: 10px;">
    <h3 class="img-center" style="border-bottom: 3px solid white; border-top-left-radius: 10px; border-top-right-radius: 10px; padding: 10px; background-color: black;">Comentários</h3>
    <p class="img-center">Poste o que achou da matéria, adoraremos saber sua opinião!</p>
    {% if exercicio.comment_set.all %}
        {% for comment in exercicio.comment_set.all %}
            <div style="background-color: rgb(255, 255, 255); color: black; border-left: 20px solid rgb(55, 55, 55); border-right: 20px solid rgb(55, 55, 55); padding-left: 10px;" >
                <p style="text-align: left; color: black;"><u><b>{{ comment.autor }}</b></u> - publicado em {{ comment.data_publicacao | date }} </p>
                <blockquote>
                    "{{ comment.texto }}"
                </blockquote>
            </div>
            <br>
        {% endfor %}
    {% else %}
        <p class="img-center">Seja o primeiro a comentar neste post.</p>
    {% endif %}
    <div class="img-center">
        <a href="{% url 'exercicios:comment' exercicio.id %}"><button type="submit">Adicionar um comentário</button></a>
    </div>
</section>

<br>
<br>
<div class="img-center">
    <a href="#" class="btn-voltar-topo"><img src="/static/Scroll_to_top.png"></a>
    <p class="img-center">Voltar para o topo</p>
</div>


{% endblock content %}

exercicios/templates/exercicios/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h2>Exercícios</h2>
<p>Confira as matérias disponíveis:</p>
<div class="lista-de-cards">

    {% if exercicio_list %}
        {% for exercicio in exercicio_list %}
        <div class="card text-center" style="width: 18rem;">
            <a href="{% url 'exercicios:detail' exercicio.id %}">
                <img class="card-img-top" src="{{ exercicio.imagem_card_url }}" alt="{{exercicio.nome_exercicio}}" height="200px">
            </a>
            <div class="card-body">
                <h5 class="card-title" id="fonte-preta">{{ exercicio.nome_exercicio }}</h5>
            </div>
        </div>
        <br>
        {% endfor %}
    {% else %}
    <p>Não foi encontrado nenhum exercício.</p>
    {% endif %}


</div>


<br>
<a href="{% url 'exercicios:create' %}"><button type="submit">Adicionar novo exercício</button></a>

<br>
<br>
<div class="img-center">
    <a href="#" class="btn-voltar-topo"><img src="/static/Scroll_to_top.png"></a>
    <p class="img-center">Voltar para o topo</p>
</div>
{% endblock content %}

exercicios/templates/exercicios/update.html
{% extends 'base.html' %}


{% block content %}

<h2>Alterar dados do exercicio: {{ exercicio.nome_exercicio }}</h2>

<form method="POST" action="{% url 'exercicios:update' exercicio.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Alterar</button>
</form>


{% endblock content %}