aiog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('exercicios/', include('exercicios.urls')),
#    path('comentarios/', include('comentarios.urls')),
#    path('accounts/', include('accounts.urls')),
#    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
#    path('api/v1/', include('api.urls')),
]

exercicios/urls.py
from django.urls import path

from . import views

app_name = 'exercicios'
urlpatterns = [
    path('', views.ExercicioListView.as_view(), name='index'),
#    path('search/', views.search_exercicios, name='search'),
    path('create/', views.create_exercicio, name='create'),
    path('<int:exercicio_id>/', views.detail_exercicio,
         name='detail'), 
    path('update/<int:exercicio_id>/', views.update_exercicio, name='update'),
    path('delete/<int:exercicio_id>/', views.delete_exercicio, name='delete'),
    path('<int:exercicio_id>/comment/', views.create_comment, name='comment'),
    path('categorias/', views.CategoryListView.as_view(), name='categorias'),
    path('categorias/create_categoria', views.CategoryCreateView.as_view(), name='create_categoria'),
#    path('import/', views.import_exercicio, name='import'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | All In One Gym
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style_moviesite.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'menu-dropdown.css' %}">
    <link rel="icon" href="{% static 'favicon_AIOG.png' %}">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</head>

<body>
    <header class="container">
        <div class="child-1">
            <a href="{% url 'index' %}"><img src="{% static 'logo_AIOG.png' %}" alt="logo" width="100%" height="100%"></a>
        </div>
        <div class="child-2">
            <h1>All In One Gym</h1>
        </div>
        <div class="child-3">
            <div class="dropdown">
                <button class="mainmenubtn"><strong>Páginas disponíveis</strong></button>
                <div class="dropdown-item"><a href="{% url 'exercicios:categorias' %}">Categorias</a></div>
                <div class="dropdown-item"><a href="{% url 'nutricao' %}">Nutrição</a></div>
                <div class="dropdown-item"><a href="{% url 'treino' %}">Treinos</a></div>
                <div class="dropdown-item"><a href="{% url 'exercicios:index' %}">Exercícios</a></div>
            </div>
        </div>
    </header>
    <br>
    <main id="container-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer>
        <p>Copyright © 2022 Renan Hideo Watanabe.</p>
    </footer>
</body>

</html>